continuation_prompt = '[❯❯ ](fg:blue)'

[git_status]
format = '[$all_status$ahead_behind]($style) '
diverged = '[↑${ahead_count}↓${behind_count}](bold yellow)'
conflicted = '[=${count}](bold red)'
ahead = '[↑${count}](bold yellow)'
behind = '[↓${count}](bold yellow)'
untracked = '[?${count}](bold cyan)'
stashed = '[#${count}](bold blue)'
modified = '[!${count}](bold yellow)'
staged = '[+${count}](bold green)'
renamed = '[R${count}](bold green)'
deleted = '[X${count}](bold red)'

[directory]
truncate_to_repo = false
truncation_symbol = '…/'

[git_branch]
format = '[$branch(:$remote_branch)]($style) '
