continuation_prompt = '[❯❯ ](fg:blue)'

[git_status]
format = '$all_status $ahead_behind '
diverged = '[￪${ahead_count}](cyan)/[￬${behind_count}](red)'
conflicted = '[=${count}](red)'
ahead = '[￪${count}](cyan)'
behind = '[￬${count}](red)'
untracked = '[?${count}](purple)'
stashed = '[#${count}](blue)'
modified = '[!${count}](yellow)'
staged = '[+${count}](green)'
renamed = '[r${count}](blue)'
deleted = '[x${count}](red)'

[directory]
format = '[$path](bold blue)[$read_only]($read_only_style) '
truncate_to_repo = false
truncation_symbol = "../"

[git_branch]
format = '[$branch(:$remote_branch)](bold purple) '

[cmd_duration]
format = ' $duration'

[lua]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[java]
disabled = true
