continuation_prompt = '[❯❯ ](fg:blue)'

[git_status]
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
conflicted = '=${count}'
ahead = '⇡${count}'
behind = '⇣${count}'
untracked = '?${count}'
stashed = '$${count}'
modified = '!${count}'
staged = '+${count}'
renamed = '»${count}'
deleted = '✘${count}'
