alias ls='ls -GF'
alias ll='ls -lGF'
alias grep='grep --color=auto'

# ctrl+wを/まで削除の挙動に
WORDCHARS=${WORDCHARS//\//}

# ls
alias sl="ls"
alias s="ls"
alias l="ls"

# Git
alias log="git log --decorate --format=format:'%C(bold cyan)%as%C(reset) %C(bold blue)%h%C(reset) %C(white bold)%<(14,trunc)%an%C(reset) %C(green)%<(38,trunc)%s%C(reset) '"
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias gl=log
alias gd="git diff"
alias gf='git pull origin $(git branch --show-current)'
alias gff='git pull'
alias gz='git stash -u'
alias gzp='git stash pop'

# === Starship
eval "$(starship init zsh)"
