
# ============================================
# 完了メッセージ
# ============================================
echo ""
log_success "======================================"
log_success " セットアップ完了！"
log_success "======================================"
echo ""
log_info "以下のコマンドで環境変数を反映してください:"
log_info "  source ~/.bashrc"
echo ""
log_info "または、一度ログアウトして再ログインしてください。"
echo ""
log_info "--- インストール済みツール ---"
log_info "・基本パッケージ (build-essential, curl, wget, etc.)"
log_info "・Git + GitHub CLI"
log_info "・fzf, ripgrep, Starship"
log_info "・Neovim, Emacs"
log_info "・pyenv + Python"
log_info "・Volta + Node.js"
log_info "・Go"
log_info "・Java (Temurin JDK)"
log_info "・Clojure, Babashka, bbin, clojure-lsp, clj-kondo, cljfmt"
log_info "・fcitx5-skk + yaskkserv2"
echo ""
log_info "--- 追加設定が必要な項目 ---"
log_info "1. yaskkserv2 を起動: systemctl --user start yaskkserv2"
log_info "2. fcitx5 設定: 再ログイン後に fcitx5-configtool を実行"
log_info "3. Neovim プラグイン: nvim を起動して :Lazy sync"
log_info "4. Emacs 設定: 必要に応じて設定ファイルを配置"
echo ""
