x-private-volumes: &private-volumes
  - ~/.claude:/root/.claude
  - ~/.claude.json:/root/.claude.json
  - ~/.claude.json.backup:/root/.claude.json.backup
  - ./setup-private.sh:/tmp/setup-private.sh:ro
  # VSCodeを使用している場合は拡張機能のインストールをキャッシュできる(以下とvolumesをコメントイン)
  - vscode-data:/root/.vscode-server
  - localbin:/usr/local/bin

services:
  server:
    volumes: *private-volumes
    command: bash /tmp/setup-private.sh server
  frontend:
    volumes: *private-volumes
    command: bash /tmp/setup-private.sh frontend

volumes:
  vscode-data:
  localbin:
